name: Release

on:
  workflow_call:
    inputs:
      prerelease:
        description: "Whether this is a prerelease"
        type: boolean
        required: true
    outputs:
      version:
        description: "The released package version"
        value: ${{ jobs.release.outputs.version }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get version
        id: version
        run: echo "version=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org

      - name: Set package version
        run: echo $(jq --arg v "${{ steps.version.outputs.version }}" '(.version) = $v' package.json) > package.json

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Publish prerelease
        if: inputs.prerelease
        run: npm publish --access public --tag=canary --provenance --no-git-checks

      - name: Publish stable release
        if: ${{ !inputs.prerelease }}
        run: npm publish --access public --provenance --no-git-checks
